name: reewer_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  sign_in_with_apple: ^4.3.0
  pin_code_fields: ^7.4.0
  flutter_native_splash:
  flutter_launcher_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.5.1

flutter_native_splash:
  background_image: assets/brand/splash_screen.png

  android_12:
    color: "#1E1929"
  web: false
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/brand/logo_foreground.png"
  adaptive_icon_foreground: "assets/brand/logo_foreground.png"
  adaptive_icon_background: "assets/brand/logo_foreground.png"
  min_sdk_android: 21



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/country/


